import { Inter } from 'next/font/google'
import './globals.css'
import CustomTheme from './CustomTheme'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3639191931415329" />
      <body className={inter.className}>
        <CustomTheme>
          {children}
        </CustomTheme>
      </body>
    </html>
  )
}
